# Favorite Trading Instruments Configuration
# Personal watchlist of preferred trading instruments

favorites:
  # Technology Stocks
  - symbol: "AAPL"
    name: "Apple Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "ABNB"
    name: "Airbnb Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "ADBE"
    name: "Adobe Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "ALT"
    name: "Altimmune Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Healthcare"
    
  - symbol: "AMD"
    name: "Advanced Micro Devices Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "AMZN"
    name: "Amazon.com Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "ARM"
    name: "Arm Holdings plc"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "ASML"
    name: "ASML Holding N.V."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "AVGO"
    name: "Broadcom Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "CRM"
    name: "Salesforce Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "CSCO"
    name: "Cisco Systems Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "DASH"
    name: "DoorDash Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "DOCN"
    name: "DigitalOcean Holdings Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "DOCU"
    name: "DocuSign Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "GOOGL"
    name: "Alphabet Inc. Class A"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "GTLB"
    name: "GitLab Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "IBM"
    name: "International Business Machines Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "INTC"
    name: "Intel Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "MSFT"
    name: "Microsoft Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "MU"
    name: "Micron Technology Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "MRVL"
    name: "Marvell Technology Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "NVDA"
    name: "NVIDIA Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "ORCL"
    name: "Oracle Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "PAYX"
    name: "Paychex Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "PEGA"
    name: "Pegasystems Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "PYPL"
    name: "PayPal Holdings Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Financials"
    
  - symbol: "QCOM"
    name: "QUALCOMM Incorporated"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "SHOP"
    name: "Shopify Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "SMCI"
    name: "Super Micro Computer Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "SPOT"
    name: "Spotify Technology S.A."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "TSM"
    name: "Taiwan Semiconductor Manufacturing Company Limited"
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "TXN"
    name: "Texas Instruments Incorporated"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    
  - symbol: "U"
    name: "Unity Software Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    
  - symbol: "UBER"
    name: "Uber Technologies Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"

  # Entertainment & Media
  - symbol: "AMC"
    name: "AMC Entertainment Holdings Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "AMCX"
    name: "AMC Networks Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "DOUL"
    name: "DoubleDown Interactive Co. Ltd."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "FOX"
    name: "Fox Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "RBLX"
    name: "Roblox Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "RDDT"
    name: "Reddit Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "WBD"
    name: "Warner Bros. Discovery Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"

  # Industrial & Manufacturing
  - symbol: "BA"
    name: "The Boeing Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    
  - symbol: "FDX"
    name: "FedEx Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    
  - symbol: "GE"
    name: "General Electric Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    
  - symbol: "GM"
    name: "General Motors Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "MANU"
    name: "Manchester United plc"
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "TM"
    name: "Toyota Motor Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "WGO"
    name: "Winnebago Industries Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"

  # International & China Stocks
  - symbol: "BABA"
    name: "Alibaba Group Holding Limited"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"

  # Energy & Utilities
  - symbol: "CLNE"
    name: "Clean Energy Fuels Corp."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Energy"
    
  - symbol: "FSLR"
    name: "First Solar Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Energy"

  # Healthcare & Biotech
  - symbol: "ABD"
    name: "Aberdine Gold Group Ltd."
    exchange: "NYSE"
    type: "stock"
    sector: "Materials"
    
  - symbol: "HIMS"
    name: "Hims & Hers Health Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    
  - symbol: "JNJ"
    name: "Johnson & Johnson"
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    
  - symbol: "MRK"
    name: "Merck & Co. Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    
  - symbol: "RVPH"
    name: "Reviva Pharmaceuticals Holdings Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Healthcare"
    
  - symbol: "UNH"
    name: "UnitedHealth Group Incorporated"
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"

  # Consumer Goods & Retail
  - symbol: "COST"
    name: "Costco Wholesale Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Staples"
    
  - symbol: "HD"
    name: "The Home Depot Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "KO"
    name: "The Coca-Cola Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    
  - symbol: "NKE"
    name: "NIKE Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "PEP"
    name: "PepsiCo Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Staples"
    
  - symbol: "PG"
    name: "The Procter & Gamble Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    
  - symbol: "PM"
    name: "Philip Morris International Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    
  - symbol: "SBUX"
    name: "Starbucks Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "TGT"
    name: "Target Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    
  - symbol: "WMT"
    name: "Walmart Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"

  # Financial Services
  - symbol: "BRK-B"
    name: "Berkshire Hathaway Inc. Class B"
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    
  - symbol: "V"
    name: "Visa Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"

  # Telecommunications
  - symbol: "T"
    name: "AT&T Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    
  - symbol: "TMUS"
    name: "T-Mobile US Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"

  # Media & Broadcasting
  - symbol: "RCAT"
    name: "Red Cat Holdings Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Industrials"
    
  - symbol: "SBGI"
    name: "Sinclair Broadcast Group Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"

  # ETFs
  - symbol: "GLD"
    name: "SPDR Gold Shares"
    exchange: "NYSE"
    type: "etf"
    category: "Precious Metals"
    
  - symbol: "IEFA"
    name: "iShares Core MSCI EAFE IMI Index ETF"
    exchange: "NYSE"
    type: "etf"
    category: "International Developed"
    
  - symbol: "SOXS"
    name: "Direxion Daily Semiconductor Bear 3X Shares"
    exchange: "NYSE"
    type: "etf"
    category: "Leveraged/Inverse"
    
  - symbol: "VOO"
    name: "Vanguard S&P 500 ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Large Cap"
    
  - symbol: "VWO"
    name: "Vanguard FTSE Emerging Markets ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Emerging Markets"