# Popular Trading Instruments Configuration
# This file contains 100 popular trading instruments including stocks, ETFs, and commodity ETFs

instruments:
  # Major Technology Stocks
  - symbol: "AAPL"
    name: "Apple Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "MSFT"
    name: "Microsoft Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "GOOGL"
    name: "Alphabet Inc. Class A"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "AMZN"
    name: "Amazon.com Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "US"
    
  - symbol: "TSLA"
    name: "Tesla Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "US"
    
  - symbol: "META"
    name: "Meta Platforms Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "NVDA"
    name: "NVIDIA Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "NFLX"
    name: "Netflix Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"
    
  - symbol: "CRM"
    name: "Salesforce Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "ORCL"
    name: "Oracle Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"

  # Financial Stocks
  - symbol: "JPM"
    name: "JPMorgan Chase & Co."
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"
    
  - symbol: "BAC"
    name: "Bank of America Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"
    
  - symbol: "WFC"
    name: "Wells Fargo & Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"
    
  - symbol: "GS"
    name: "The Goldman Sachs Group Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"
    
  - symbol: "V"
    name: "Visa Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"

  # Healthcare Stocks
  - symbol: "JNJ"
    name: "Johnson & Johnson"
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    currency: "USD"
    country: "US"
    
  - symbol: "PFE"
    name: "Pfizer Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    currency: "USD"
    country: "US"
    
  - symbol: "UNH"
    name: "UnitedHealth Group Incorporated"
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    currency: "USD"
    country: "US"
    
  - symbol: "ABBV"
    name: "AbbVie Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    currency: "USD"
    country: "US"
    
  - symbol: "MRK"
    name: "Merck & Co. Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Healthcare"
    currency: "USD"
    country: "US"

  # Energy Stocks
  - symbol: "XOM"
    name: "Exxon Mobil Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Energy"
    currency: "USD"
    country: "US"
    
  - symbol: "CVX"
    name: "Chevron Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Energy"
    currency: "USD"
    country: "US"
    
  - symbol: "COP"
    name: "ConocoPhillips"
    exchange: "NYSE"
    type: "stock"
    sector: "Energy"
    currency: "USD"
    country: "US"

  # Industrial Stocks
  - symbol: "BA"
    name: "The Boeing Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    currency: "USD"
    country: "US"
    
  - symbol: "CAT"
    name: "Caterpillar Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    currency: "USD"
    country: "US"
    
  - symbol: "GE"
    name: "General Electric Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Industrials"
    currency: "USD"
    country: "US"

  # Consumer Goods
  - symbol: "KO"
    name: "The Coca-Cola Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    currency: "USD"
    country: "US"
    
  - symbol: "PG"
    name: "The Procter & Gamble Company"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    currency: "USD"
    country: "US"
    
  - symbol: "WMT"
    name: "Walmart Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Staples"
    currency: "USD"
    country: "US"
    
  - symbol: "HD"
    name: "The Home Depot Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "US"
    
  - symbol: "MCD"
    name: "McDonald's Corporation"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "US"

  # Telecommunications
  - symbol: "VZ"
    name: "Verizon Communications Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"
    
  - symbol: "T"
    name: "AT&T Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"

  # International Stocks
  - symbol: "BABA"
    name: "Alibaba Group Holding Limited"
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "CN"
    
  - symbol: "TSM"
    name: "Taiwan Semiconductor Manufacturing Company Limited"
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "TW"
    
  - symbol: "ASML"
    name: "ASML Holding N.V."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "NL"

  # Major Market ETFs
  - symbol: "SPY"
    name: "SPDR S&P 500 ETF Trust"
    exchange: "NYSE"
    type: "etf"
    category: "Large Cap"
    expense_ratio: 0.0945
    currency: "USD"
    country: "US"
    
  - symbol: "QQQ"
    name: "Invesco QQQ Trust"
    exchange: "NASDAQ"
    type: "etf"
    category: "Technology"
    expense_ratio: 0.20
    currency: "USD"
    country: "US"
    
  - symbol: "IWM"
    name: "iShares Russell 2000 ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Small Cap"
    expense_ratio: 0.19
    currency: "USD"
    country: "US"
    
  - symbol: "VTI"
    name: "Vanguard Total Stock Market ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Total Market"
    expense_ratio: 0.03
    currency: "USD"
    country: "US"
    
  - symbol: "VOO"
    name: "Vanguard S&P 500 ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Large Cap"
    expense_ratio: 0.03
    currency: "USD"
    country: "US"
    
  - symbol: "VEA"
    name: "Vanguard FTSE Developed Markets ETF"
    exchange: "NYSE"
    type: "etf"
    category: "International Developed"
    expense_ratio: 0.05
    currency: "USD"
    country: "US"
    
  - symbol: "VWO"
    name: "Vanguard FTSE Emerging Markets ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Emerging Markets"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "EFA"
    name: "iShares MSCI EAFE ETF"
    exchange: "NYSE"
    type: "etf"
    category: "International Developed"
    expense_ratio: 0.32
    currency: "USD"
    country: "US"
    
  - symbol: "EEM"
    name: "iShares MSCI Emerging Markets ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Emerging Markets"
    expense_ratio: 0.68
    currency: "USD"
    country: "US"
    
  - symbol: "AGG"
    name: "iShares Core U.S. Aggregate Bond ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Bonds"
    expense_ratio: 0.03
    currency: "USD"
    country: "US"

  # Sector ETFs
  - symbol: "XLK"
    name: "Technology Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Technology"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLF"
    name: "Financial Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Financials"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLE"
    name: "Energy Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Energy"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLV"
    name: "Health Care Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Healthcare"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLI"
    name: "Industrial Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Industrials"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLP"
    name: "Consumer Staples Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Consumer Staples"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLY"
    name: "Consumer Discretionary Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Consumer Discretionary"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLU"
    name: "Utilities Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Utilities"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"
    
  - symbol: "XLRE"
    name: "Real Estate Select Sector SPDR Fund"
    exchange: "NYSE"
    type: "etf"
    category: "Real Estate"
    expense_ratio: 0.10
    currency: "USD"
    country: "US"

  # Commodity ETFs
  - symbol: "GLD"
    name: "SPDR Gold Shares"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Gold"
    expense_ratio: 0.40
    currency: "USD"
    country: "US"
    
  - symbol: "SLV"
    name: "iShares Silver Trust"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Silver"
    expense_ratio: 0.50
    currency: "USD"
    country: "US"
    
  - symbol: "USO"
    name: "United States Oil Fund LP"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Crude Oil"
    expense_ratio: 0.87
    currency: "USD"
    country: "US"
    
  - symbol: "UNG"
    name: "United States Natural Gas Fund LP"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Natural Gas"
    expense_ratio: 1.28
    currency: "USD"
    country: "US"
    
  - symbol: "DBA"
    name: "Invesco DB Agriculture Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Agriculture"
    expense_ratio: 0.85
    currency: "USD"
    country: "US"
    
  - symbol: "DBC"
    name: "Invesco DB Commodity Index Tracking Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Diversified Commodities"
    expense_ratio: 0.85
    currency: "USD"
    country: "US"
    
  - symbol: "PDBC"
    name: "Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF"
    exchange: "NASDAQ"
    type: "commodity_etf"
    commodity: "Diversified Commodities"
    expense_ratio: 0.59
    currency: "USD"
    country: "US"
    
  - symbol: "GSG"
    name: "iShares S&P GSCI Commodity-Indexed Trust"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Diversified Commodities"
    expense_ratio: 0.75
    currency: "USD"
    country: "US"
    
  - symbol: "CORN"
    name: "Teucrium Corn Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Corn"
    expense_ratio: 1.15
    currency: "USD"
    country: "US"
    
  - symbol: "WEAT"
    name: "Teucrium Wheat Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Wheat"
    expense_ratio: 1.15
    currency: "USD"
    country: "US"
    
  - symbol: "SOYB"
    name: "Teucrium Soybean Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Soybeans"
    expense_ratio: 1.15
    currency: "USD"
    country: "US"
    
  - symbol: "CANE"
    name: "Teucrium Sugar Fund"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Sugar"
    expense_ratio: 1.15
    currency: "USD"
    country: "US"
    
  - symbol: "NIB"
    name: "iPath Bloomberg Cocoa Subindex Total Return ETN"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Cocoa"
    expense_ratio: 0.45
    currency: "USD"
    country: "US"
    
  - symbol: "JO"
    name: "iPath Bloomberg Coffee Subindex Total Return ETN"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Coffee"
    expense_ratio: 0.45
    currency: "USD"
    country: "US"
    
  - symbol: "PPLT"
    name: "abrdn Physical Platinum Shares ETF"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Platinum"
    expense_ratio: 0.60
    currency: "USD"
    country: "US"
    
  - symbol: "PALL"
    name: "abrdn Physical Palladium Shares ETF"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Palladium"
    expense_ratio: 0.60
    currency: "USD"
    country: "US"

  # Cryptocurrency ETFs
  - symbol: "BITO"
    name: "ProShares Bitcoin Strategy ETF"
    exchange: "NYSE"
    type: "commodity_etf"
    commodity: "Bitcoin Futures"
    expense_ratio: 0.95
    currency: "USD"
    country: "US"

  # Additional Popular Stocks
  - symbol: "AMD"
    name: "Advanced Micro Devices Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "INTC"
    name: "Intel Corporation"
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "ADBE"
    name: "Adobe Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "PYPL"
    name: "PayPal Holdings Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Financials"
    currency: "USD"
    country: "US"
    
  - symbol: "SHOP"
    name: "Shopify Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "CA"
    
  - symbol: "SQ"
    name: "Block Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "SPOT"
    name: "Spotify Technology S.A."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "SE"
    
  - symbol: "UBER"
    name: "Uber Technologies Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "LYFT"
    name: "Lyft Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "ZOOM"
    name: "Zoom Video Communications Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "ROKU"
    name: "Roku Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "TWTR"
    name: "Twitter Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"
    
  - symbol: "SNAP"
    name: "Snap Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"
    
  - symbol: "PINS"
    name: "Pinterest Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Communication Services"
    currency: "USD"
    country: "US"
    
  - symbol: "TWLO"
    name: "Twilio Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "OKTA"
    name: "Okta Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "SNOW"
    name: "Snowflake Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "PLTR"
    name: "Palantir Technologies Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Technology"
    currency: "USD"
    country: "US"
    
  - symbol: "NIO"
    name: "NIO Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "CN"
    
  - symbol: "XPEV"
    name: "XPeng Inc."
    exchange: "NYSE"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "CN"
    
  - symbol: "LI"
    name: "Li Auto Inc."
    exchange: "NASDAQ"
    type: "stock"
    sector: "Consumer Discretionary"
    currency: "USD"
    country: "CN"

  # Additional ETFs
  - symbol: "ARKK"
    name: "ARK Innovation ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Innovation"
    expense_ratio: 0.75
    currency: "USD"
    country: "US"
    
  - symbol: "TLT"
    name: "iShares 20+ Year Treasury Bond ETF"
    exchange: "NASDAQ"
    type: "etf"
    category: "Long-Term Bonds"
    expense_ratio: 0.15
    currency: "USD"
    country: "US"
    
  - symbol: "HYG"
    name: "iShares iBoxx $ High Yield Corporate Bond ETF"
    exchange: "NYSE"
    type: "etf"
    category: "High Yield Bonds"
    expense_ratio: 0.49
    currency: "USD"
    country: "US"
    
  - symbol: "LQD"
    name: "iShares iBoxx $ Investment Grade Corporate Bond ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Investment Grade Bonds"
    expense_ratio: 0.14
    currency: "USD"
    country: "US"
    
  - symbol: "VNQ"
    name: "Vanguard Real Estate ETF"
    exchange: "NYSE"
    type: "etf"
    category: "Real Estate"
    expense_ratio: 0.12
    currency: "USD"
    country: "US"